### variable
@urlLink=http://localhost:8000/api/v1/users/
@urlTransaction=http://localhost:8000/api/v1/transaction/

### GET  to do with user login
POST {{urlLink}}login
Content-Type: application/json

{
    "email":"nouyadin@gmail.com",
    "password":"123"
}


### GET  to do with user profile
GET http://localhost:8000/api/v1/users/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5vdXlhZGluQGdtYWlsLmNvbSIsImlhdCI6MTc4NzM3ODg1NywiZXhwIjoxNzg3NDY1MjU3fQ.K8m7Ir9GCaSZbVDTXAA6_eHbPLAo8cQe4QUZhh1oQnY

### POST to sign up
POST {{urlLink}}signup
Content-Type: application/json

{
    "name":"nouyadin",
    "email":"nouyadin@gmail.com",
    "gender":"male",
    "password":"12345"
}

### Transaction section

### POST to add transaction
POST {{urlTransaction}}
Content-Type: application/json

{
    "userID":"6a837551dc83cb97e8ee9e78",
    "type":"expanses",
    "title":"exercise",
    "amount":22.5,
    "date":"2026-08-22",
    "headers":{
        "Authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5vdXlhZGluQGdtYWlsLmNvbSIsImlhdCI6MTc4NzM3ODg1NywiZXhwIjoxNzg3NDY1MjU3fQ.K8m7Ir9GCaSZbVDTXAA6_eHbPLAo8cQe4QUZhh1oQnY"
    }
}