### variable
@urlLink=http://localhost:8000/api/v1/users/

### GET  to do with user login
POST {{urlLink}}login
Content-Type: application/json

{
    "email":"nouyadin@gmail.com",
    "password":"123"
}


### GET  to do with user profile
GET http://localhost:8000/api/v1/users/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5vdXlhZGluQGdtYWlsLmNvbSIsImlhdCI6MTc4NzI1NjQ1OSwiZXhwIjoxNzg3MjU2NTE5fQ.GtKRlczUuuUR5abGLLC7F8dtvL9I1r8izHP8ZaTbihI




### POST to do
POST {{urlLink}}signup
Content-Type: application/json

{
    "name":"nouyadin",
    "email":"nouyadin@gmail.com",
    "gender":"male",
    "password":"12345"
}