### variable
@urlLink=http://localhost:8000/api/v1/users/

### GET  to do with user login
POST {{urlLink}}login
Content-Type: application/json

{
    "email":"nouyadin@gmail.com",
    "password":"123"
}


### GET  to do with user profile
GET http://localhost:8000/api/v1/users/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5vdXlhZGluQGdtYWlsLmNvbSIsImlhdCI6MTc4NzM0MTY1NSwiZXhwIjoxNzg3NDI4MDU1fQ.B6jRH9SxFPdJ2Ri7sQoF52qbxSvhsEFeftJNpvc_MfE



### POST to sign up
POST {{urlLink}}signup
Content-Type: application/json

{
    "name":"nouyadin",
    "email":"nouyadin@gmail.com",
    "gender":"male",
    "password":"12345"
}

### POST to add transaction
POST {{urlLink}}transaction
Content-Type: application/json

{
    "type":"expanses",
    "title":"food",
    "amount":22.5,
    "date":"2026-08-22"
}